/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: ff26f4368771ef184e0b78008a57b62b)
interface __BaseEnv_Env {
	AGENT_MODEL: string;
	USER_KEY_ENCRYPTION_KEY: string;
	AGENT_SESSIONS: DurableObjectNamespace<import("./dist/worker").AgentSession>;
	USERS: DurableObjectNamespace<import("./dist/worker").User>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./dist/worker");
		durableNamespaces: "AgentSession" | "User";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AGENT_MODEL" | "USER_KEY_ENCRYPTION_KEY">> {}
}
declare module "*.txt" {
	const value: string;
	export default value;
}
declare module "*.html" {
	const value: string;
	export default value;
}
declare module "*.sql" {
	const value: string;
	export default value;
}
declare module "*.bin" {
	const value: ArrayBuffer;
	export default value;
}
declare module "*.wasm" {
	const value: WebAssembly.Module;
	export default value;
}
declare module "*.wasm?module" {
	const value: WebAssembly.Module;
	export default value;
}